import { describe, it, expect } from 'vitest';
import { REPOS } from '../../worker/src/repos';
import { projects } from '../../site/src/data/projects';

// Static Astro page slugs generated by [pkg].astro
const astroSlugs = new Set(projects.map(p => p.name));

// Worker dynamic route keys (top-level only)
const workerKeys = new Set(
  Object.keys(REPOS).filter(k => !k.includes('/')),
);

// Reserved paths the worker handles specially
const WORKER_RESERVED = new Set([
  '_astro',
  'favicon.svg',
  'houston.webp',
  'starlight',
  'pagefind',
  'fonts',
  'images',
]);

describe('route-conflicts: no slug collisions', () => {
  it('no Astro static slug duplicates a reserved worker path', () => {
    const conflicts = [...astroSlugs].filter(s => WORKER_RESERVED.has(s));
    expect(
      conflicts,
      'Astro slugs collide with worker reserved paths',
    ).toEqual([]);
  });

  it('Astro slugs are a subset of worker REPOS keys', () => {
    // Every [pkg].astro page should correspond to a known repo
    const unknown = [...astroSlugs].filter(s => !workerKeys.has(s));
    expect(
      unknown,
      'Astro slugs without matching worker REPOS entry',
    ).toEqual([]);
  });

  it('PROXIED_SUBDOMAINS excludes "hop"', () => {
    // Worker filters out "hop" from proxied subdomains
    const proxied = Object.keys(REPOS).filter(name => name !== 'hop');
    expect(proxied).not.toContain('hop');
  });

  it('"hop" key exists in REPOS', () => {
    expect(REPOS['hop']).toBeDefined();
  });

  it('no REPOS key matches a reserved static-asset pattern', () => {
    const conflicts = [...workerKeys].filter(k => WORKER_RESERVED.has(k));
    expect(
      conflicts,
      'REPOS keys that collide with static-asset patterns',
    ).toEqual([]);
  });
});
