#!/bin/bash
# Tests for scripts/generate-repo-map.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT="$SCRIPT_DIR/generate-repo-map.sh"
PASS=0
FAIL=0

pass() { PASS=$((PASS + 1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  FAIL: $1 — $2"; }

echo "=== generate-repo-map.sh tests ==="

# Test: script is executable
if [ -x "$SCRIPT" ]; then
  pass "script is executable"
else
  fail "script is executable" "missing +x permission"
fi

# Test: script uses pipefail
if grep -q 'set -euo pipefail' "$SCRIPT"; then
  pass "script uses pipefail"
else
  fail "script uses pipefail" "should use set -euo pipefail"
fi

# Test: output path targets worker/src/repos.ts
if grep -q 'FILE="worker/src/repos.ts"' "$SCRIPT"; then
  pass "output path is worker/src/repos.ts"
else
  fail "output path is worker/src/repos.ts" "unexpected output path"
fi

# Test: output is valid TypeScript export syntax
OUTPUT_FILE="$SCRIPT_DIR/../worker/src/repos.ts"
if [ -f "$OUTPUT_FILE" ]; then
  if head -1 "$OUTPUT_FILE" | grep -q '^// Generated by'; then
    pass "output has generated header"
  else
    fail "output has generated header" "missing header comment"
  fi

  if grep -q 'export const REPOS: Record<string, string>' "$OUTPUT_FILE"; then
    pass "output has valid TypeScript export"
  else
    fail "output has valid TypeScript export" "missing export declaration"
  fi

  if tail -1 "$OUTPUT_FILE" | grep -q '};'; then
    pass "output closes object correctly"
  else
    fail "output closes object correctly" "missing closing };"
  fi
else
  fail "output file exists" "$OUTPUT_FILE not found"
fi

# Test: script resolves default branch (not HEAD)
if grep -q 'default_branch' "$SCRIPT"; then
  pass "resolves default branch for tree API"
else
  fail "resolves default branch for tree API" \
    "uses HEAD instead of default branch"
fi

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
