#!/bin/bash
set -e

# Fetch repo names from hop-top org
REPOS=$(gh repo list hop-top --limit 100 --json name --jq '.[].name' | grep -v '^\.')

# Start generating TypeScript file
FILE="worker/src/repos.ts"
echo "// Generated by scripts/generate-repo-map.sh - DO NOT EDIT" > "$FILE"
echo "export const REPOS: Record<string, string> = {" >> "$FILE"

for repo in $REPOS; do
  echo "  \"$repo\": \"https://github.com/hop-top/$repo\"," >> "$FILE"

  # Detect Go submodules (dirs with go.mod at depth 1)
  submods=$(gh api "repos/hop-top/$repo/git/trees/HEAD?recursive=1" \
    --jq '[.tree[] | select(.path | test("^[^/]+/go\\.mod$"))] | .[].path | gsub("/go\\.mod$"; "")' 2>/dev/null || true)
  for subdir in $submods; do
    echo "  \"$repo/$subdir\": \"https://github.com/hop-top/$repo\"," >> "$FILE"
  done
done

echo "};" >> "$FILE"

echo "Generated $FILE with $(grep -c '"https://' "$FILE") entries."
